// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Item_copyright: typeof import('./components/Item_copyright/Item_copyright.vue')['default']
    Item_Name_Icon: typeof import('./components/Item_Name_Icon/Item_Name_Icon.vue')['default']
    Login_Register: typeof import('./components/Login_Register/Login_Register.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
